### ISSUE TITLE
It does not seem to autocomplete namespace name

### ISSUE THREAD

**Issue by andrewsav-bt** [mziyabo/PSKubectlCompletion#7]
When I type `k get pod -n startOfNamespaceName<tab>` I'm not getting autocompletion on the namespace name. Am I doing it wrong?

**Comment by Aankhen** [comment]
I see the same behaviour.

**Comment by lukasvosyka** [comment]
Quite good but renders useless without autocompletion for namespaces

**Comment by Aankhen** [comment]
Just a heads up: [kubectl v1.23.0 will include native PowerShell completion](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.23.md#feature-4) ([the documentation has been updated too](https://github.com/kubernetes/website/pull/29610/)). I’m running the RC. It has some rough edges but, for one thing, it recognizes context and namespace flags. Once released, it should render it unnecessary to use PSKubectlCompletion. (And of course, you could start using the RC right away like me if you wanted.)

EDIT:
[Kubernetes (and therefore kubectl) v1.23.0 is out now with builtin PowerShell completion.](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.23.md#changelog-since-v1220)

**Comment by mziyabo** [comment]
Closing as the repository is being archived.
